### ISSUE TITLE
Make migration file for simple Todolist

### ISSUE THREAD

**Issue by k-okina** [k-okina/todolist#1]
- [x] Users
* columns
  * id increments
  * name string unique
  * email string unique
  * password string
  * facebook_id unsignedBigInteger unique nullable
  * twitter_id unsignedBigInteger unique nullable
  * google_id unsignedBigInteger unique nullable
  * is_deleted boolean default(0)
  * timestamps

---
- [x] Profiles
* columns
  * id increments
  * user_id unsignedInteger
  * user_name string
  * gender string
  * thumbnail_url string nullable
  * tweet string nullable
  * description string nullable
  * timestamps
* foreign keys
  * foreign user_id references id on users

---
- [x] Todolists
* columns
  * id increments
  * user_id unsignedInteger
  * title string
  * urgency integer default(4)
  * importance integer default(4)
  * is_finished boolean default(0)
  * is_deleted boolean default(0)
  * timestamps

---
- [x] TodolistMessages
* columns
  * id increments
  * todolist_id unsignedInteger
  * user_id unsignedInteger
  * message text
* foreign keys
  * foreign user_id references id on users
  * foreign chatroom_id references id on chatrooms

---
- [x] Follows
* columns
  * id increments
  * user_id unsignedInteger
  * follow_user_id unsignedInteger
  * timestamps
* foreign keys
  * foreign user_id references id on users
  * foreign follow_user_id references id on users

**Comment by k-okina** [comment]
頑張るぞ〜！

**Comment by takeokunn** [comment]
いいね〜

**Comment by k-okina** [comment]
せやで
明日の朝も続きやろ〜
